name: Build and Jekyll site and run htmlproofer

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Fetch main
        run: |
          git fetch origin main --depth 1
          git branch

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: Use cache to shorten build time
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
          build_dir: _site

      - name: Check links with lychee
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: --verbose --no-progress _site/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@v2
        with:
          directory: "_site"
          arguments: |
            --ignore-urls "https://www.github.com,https://fonts.googleapis.com,https://fonts.gstatic.com,_site/_posts/README/index.html"
            --ignore-files "/.+\/_posts\/README.md"
            --ignore-status-codes "0, 200, 403, 429, 503, 999"
